services:
  postgres:
    image: postgres:latest
    container_name: docker-postgres
    environment:
      POSTGRES_DB: findjob
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: docker-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Логин для pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin123        # Пароль для pgAdmin
    ports:
      - "5051:80"  # pgAdmin будет доступен на http://localhost:5050
    depends_on:
      - postgres

volumes:
  postgres_data: