spring:
  application:
    name: user-service-ms
  config:
    import: optional:configserver:http://localhost:8888


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
